"""
backend/api/test_inference_service.py
======================================
Standalone smoke-test for the ML inference pipeline.

Run from the project root with the .venv-inference environment:
    backend\\.venv-inference\\Scripts\\python.exe backend\\api\\test_inference_service.py

What this tests:
  - Model initialization (TranSalNet, FusionNetwork, PaddleOCR, YuNet, YOLO-World-S)
  - Full 8-channel feature generation for one real OSIE test image
  - Correct spatial map shapes, dtypes, ranges, and finiteness
  - Correct Fusion input/output tensor shapes
  - Overlay PNG generation

Does NOT touch:
  - FastAPI, HTTP, JWT authentication
  - MongoDB
  - Cloudinary
"""

# Windows: must register System32 before ANY native extension imports (cv2, torch).
import os
if os.name == "nt":
    os.add_dll_directory(r"C:\Windows\System32")

import sys
import traceback
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Path bootstrap — ensure backend root is resolvable regardless of CWD
# ──────────────────────────────────────────────────────────────────────────────
THIS_FILE   = Path(__file__).resolve()
API_DIR     = THIS_FILE.parent
BACKEND_DIR = API_DIR.parent
PROJECT_ROOT = BACKEND_DIR.parent

# Prepend backend to sys.path so "api.inference_service" is importable
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# ──────────────────────────────────────────────────────────────────────────────
# 3rd-party imports (available in .venv-fusion)
# ──────────────────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd

# ──────────────────────────────────────────────────────────────────────────────
# Paths — derived from existing fusion/config.py conventions
# No paths are hardcoded; all come from the project layout.
# ──────────────────────────────────────────────────────────────────────────────
DATA_BASE_DIR  = BACKEND_DIR / "person_c" / "data" / "processed" / "osie"
MANIFEST_PATH  = DATA_BASE_DIR / "feature_manifest.csv"
TEST_CSV_PATH  = DATA_BASE_DIR / "test.csv"
IMAGES_DIR     = DATA_BASE_DIR / "images"

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────
PASS = "\033[92m[PASS]\033[0m"
FAIL = "\033[91m[FAIL]\033[0m"
INFO = "\033[94m[INFO]\033[0m"


def ok(msg):
    print(f"  {PASS} {msg}")


def fail(msg):
    print(f"  {FAIL} {msg}")
    sys.exit(1)


def info(msg):
    print(f"  {INFO} {msg}")


def assert_map(m, name):
    """Validate a single spatial map against the frozen data contract."""
    if m is None:
        fail(f"{name}: returned None")
    if m.shape != (288, 384):
        fail(f"{name}: wrong shape {m.shape}, expected (288, 384)")
    if m.dtype.name != "float32":
        fail(f"{name}: wrong dtype {m.dtype}, expected float32")
    if not np.isfinite(m).all():
        fail(f"{name}: contains NaN or Inf")
    if m.min() < 0.0 or m.max() > 1.0001:
        fail(f"{name}: values out of [0,1] range (min={m.min():.4f}, max={m.max():.4f})")
    ok(f"{name}: shape={m.shape} dtype={m.dtype} min={m.min():.4f} max={m.max():.4f}")


# ──────────────────────────────────────────────────────────────────────────────
# Step 1 — Resolve a deterministic test image from the existing test split
# ──────────────────────────────────────────────────────────────────────────────
def resolve_test_image():
    """
    Reads the existing deterministic test.csv (generated by the Fusion dataloader
    with seed=42) and returns the path to the first image.
    Falls back to the manifest if test.csv is absent.
    """
    if TEST_CSV_PATH.exists():
        df = pd.read_csv(TEST_CSV_PATH)
        source = "test.csv"
    elif MANIFEST_PATH.exists():
        # Reproduce the same seed-42 split used during training
        df_full = pd.read_csv(MANIFEST_PATH)
        df_full = df_full.sample(frac=1, random_state=42).reset_index(drop=True)
        n = len(df_full)
        train_end = int(0.70 * n)
        val_end   = int(0.85 * n)
        df = df_full.iloc[val_end:].reset_index(drop=True)
        source = "feature_manifest.csv (split reproduced)"
    else:
        print(f"\n{FAIL} Neither test.csv nor feature_manifest.csv found under:")
        print(f"         {DATA_BASE_DIR}")
        sys.exit(1)

    if df.empty:
        fail("Test split is empty.")

    first_id = str(df.iloc[0]["image_id"])
    img_path = IMAGES_DIR / f"{first_id}.jpg"

    if not img_path.exists():
        fail(f"Image file not found: {img_path}")

    info(f"Test image source: {source}")
    info(f"Image ID:          {first_id}")
    info(f"Image path:        {img_path}")
    return str(img_path), first_id


# ──────────────────────────────────────────────────────────────────────────────
# Step 2 — Load image bytes (what the real route does)
# ──────────────────────────────────────────────────────────────────────────────
def load_image_bytes(img_path: str) -> bytes:
    with open(img_path, "rb") as f:
        return f.read()


# ──────────────────────────────────────────────────────────────────────────────
# Main smoke-test
# ──────────────────────────────────────────────────────────────────────────────
def main():
    print("\n" + "="*60)
    print("  ThumbHeap ML Inference Smoke-Test")
    print("="*60 + "\n")

    # ── Step 1: Resolve test image ───────────────────────────────────────────
    print("[ 1/5 ] Resolving deterministic test image...")
    img_path, img_id = resolve_test_image()
    image_bytes = load_image_bytes(img_path)
    ok(f"Image loaded: {len(image_bytes):,} bytes")

    # ── Step 2: Import & initialize models ───────────────────────────────────
    print("\n[ 2/5 ] Loading models...")
    print("        (TranSalNet, FusionNetwork, PaddleOCR, YuNet, YOLO-World-S)")
    print("        This may take 30-90 seconds on first run.\n")

    try:
        import api.inference_service as svc
    except ImportError as exc:
        print(f"\n{FAIL} Could not import inference_service:")
        traceback.print_exc()
        sys.exit(1)

    try:
        svc.initialize()
    except FileNotFoundError as exc:
        print(f"\n{FAIL} Missing model file:\n  {exc}")
        sys.exit(1)
    except Exception as exc:
        # Attempt to identify the responsible component
        tb_str = traceback.format_exc()
        if "TranSalNet" in tb_str or "transalnet" in tb_str.lower() or "skimage" in tb_str or "scipy" in tb_str:
            print(f"\n{FAIL} TranSalNet initialization failed (possible missing package or DLL issue):")
        elif "PaddleOCR" in tb_str or "paddle" in tb_str.lower():
            print(f"\n{FAIL} PaddleOCR initialization failed:")
        elif "yunet" in tb_str.lower() or "FaceDetector" in tb_str:
            print(f"\n{FAIL} YuNet initialization failed:")
        elif "YOLO" in tb_str or "ultralytics" in tb_str.lower():
            print(f"\n{FAIL} YOLO-World initialization failed:")
        elif "FusionNetwork" in tb_str or "fusion" in tb_str.lower():
            print(f"\n{FAIL} FusionNetwork initialization failed:")
        else:
            print(f"\n{FAIL} Model initialization failed (unknown component):")
        traceback.print_exc()
        sys.exit(1)

    ok("TranSalNet-Res loaded")
    ok("FusionNetwork loaded")
    ok("PaddleOCR loaded")
    ok("YuNet loaded")
    ok("YOLO-World-S loaded")

    # ── Step 3: Run full inference ───────────────────────────────────────────
    print(f"\n[ 3/5 ] Running inference on image {img_id}...")

    try:
        result = svc.run_inference(image_bytes)
    except ValueError as exc:
        print(f"\n{FAIL} Image decode failed (invalid file): {exc}")
        sys.exit(1)
    except Exception as exc:
        tb_str = traceback.format_exc()
        # Identify component responsible for the failure
        if "TranSalNet" in tb_str or "transalnet" in tb_str.lower() or "preprocess_img" in tb_str:
            print(f"\n{FAIL} Failure occurred in TranSalNet inference step:")
        elif "detect_text" in tb_str or "PaddleOCR" in tb_str or "paddle" in tb_str.lower():
            print(f"\n{FAIL} Failure occurred in PaddleOCR / text_map step:")
        elif "detect_face" in tb_str or "FaceDetector" in tb_str or "yunet" in tb_str.lower():
            print(f"\n{FAIL} Failure occurred in YuNet / face_map step:")
        elif "detect_object" in tb_str or "YOLO" in tb_str or "ultralytics" in tb_str.lower():
            print(f"\n{FAIL} Failure occurred in YOLO-World / object_map step:")
        elif "_opencv_maps" in tb_str or "feature_extractor" in tb_str:
            print(f"\n{FAIL} Failure occurred in OpenCV feature extraction step:")
        elif "FusionNetwork" in tb_str or "_fusion_net" in tb_str:
            print(f"\n{FAIL} Failure occurred in FusionNetwork inference step:")
        elif "_build_overlay" in tb_str:
            print(f"\n{FAIL} Failure occurred in overlay generation step:")
        else:
            print(f"\n{FAIL} Inference failed at an unidentified step:")
        traceback.print_exc()
        sys.exit(1)

    ok("run_inference() completed without exception")

    # ── Step 4: Validate all 8 spatial maps ─────────────────────────────────
    print("\n[ 4/5 ] Validating feature maps and tensor shapes...")

    # The inference service returns the numeric heatmap array and overlay bytes.
    # We rebuild and validate the 8 individual channel maps by re-running
    # the internal helpers directly with the same image so we can inspect each
    # channel independently without duplicating inference logic.
    heatmap = result["heatmap_array"]
    overlay_png = result["overlay_png"]
    detections  = result["detections"]

    # Validate final Fusion output
    if heatmap.shape != (288, 384):
        fail(f"Fusion output shape wrong: {heatmap.shape}, expected (288, 384)")
    if heatmap.dtype.name != "float32":
        fail(f"Fusion output dtype wrong: {heatmap.dtype}, expected float32")
    if not np.isfinite(heatmap).all():
        fail("Fusion output contains NaN or Inf")
    if heatmap.min() < 0.0 or heatmap.max() > 1.0001:
        fail(f"Fusion output out of [0,1]: min={heatmap.min():.4f} max={heatmap.max():.4f}")
    ok(f"Fusion heatmap: shape={heatmap.shape} dtype={heatmap.dtype} "
       f"min={heatmap.min():.4f} max={heatmap.max():.4f}")

    # Validate overlay bytes
    if not overlay_png or len(overlay_png) == 0:
        fail("Overlay PNG is empty")
    ok(f"Overlay PNG: {len(overlay_png):,} bytes")

    # Validate detection metadata
    for key in ("texts", "faces", "objects"):
        if not isinstance(detections.get(key), int):
            fail(f"detections['{key}'] is missing or not an int")
    ok(f"Detections: texts={detections['texts']} faces={detections['faces']} "
       f"objects={detections['objects']}")

    # ── Step 5: Re-run individual map generation for per-channel validation ──
    print("\n[ 5/5 ] Per-channel map validation (re-runs map generation)...")
    import tempfile, cv2

    # Write temp file for path-based APIs
    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
        tmp_path = tmp.name
        tmp.write(image_bytes)

    try:
        # Base heatmap (TranSalNet)
        try:
            bh = svc._transalnet_heatmap(tmp_path)
            assert_map(bh, "base_heatmap   [ch 0]")
        except Exception as exc:
            tb_str = traceback.format_exc()
            print(f"\n{FAIL} TranSalNet base heatmap generation failed:")
            traceback.print_exc()
            sys.exit(1)

        # text_map (EasyOCR)
        from detection.ocr_easyocr import detect_text_and_map
        _, text_map, _, _ = detect_text_and_map(tmp_path, svc._ocr_model)
        assert_map(text_map, "text_map       [ch 1]")

        # face_map (YuNet)
        from detection.yunet import detect_faces_and_map
        _, face_map, _, _ = detect_faces_and_map(tmp_path, svc._yunet)
        assert_map(face_map, "face_map       [ch 2]")

        # object_map (YOLO-World)
        from detection.yolo_world import detect_objects_and_map
        _, obj_map, _, _ = detect_objects_and_map(tmp_path, svc._yolo)
        assert_map(obj_map, "object_map     [ch 3]")

        # OpenCV maps
        orig_bgr = cv2.imread(tmp_path)
        brightness, contrast, saturation, edge = svc._opencv_maps(orig_bgr)
        assert_map(brightness, "brightness_map [ch 4]")
        assert_map(contrast,   "contrast_map   [ch 5]")
        assert_map(saturation, "saturation_map [ch 6]")
        assert_map(edge,       "edge_map       [ch 7]")

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    # ── Final summary ────────────────────────────────────────────────────────
    print("\n" + "="*60)
    print("  ALL BACKEND INFERENCE TESTS PASSED.")
    print("="*60 + "\n")


if __name__ == "__main__":
    main()
